<Project>
  <PropertyGroup>
    <Version>0.1.4</Version>

    <TargetFramework>net10.0</TargetFramework>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <InformationalVersion>$(Version)$(VersionSuffix)</InformationalVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

    <AspNetVersion>10.0.1</AspNetVersion>
  </PropertyGroup>
</Project>
