// Generated by Bottleneko.CodeGenerator
/* eslint-disable @typescript-eslint/no-confusing-void-expression */

import type * as bottleneko from './bottleneko.gen';

export type ResultType<T, Default> = 'result' extends keyof T ? T['result'] : Default;

export default abstract class AbstractRpc {
    chatters = {
        async list(args: Omit<bottleneko.ChattersListRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ChattersListResponse>({ $type: 'Chatters/List', ...args }); },
        async get(args: Omit<bottleneko.ChattersGetRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ChattersGetResponse>({ $type: 'Chatters/Get', ...args }); },
    };
    connections = {
        async list(args: Omit<bottleneko.ConnectionsListRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ConnectionsListResponse>({ $type: 'Connections/List', ...args }); },
        async get(args: Omit<bottleneko.ConnectionsGetRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ConnectionsGetResponse>({ $type: 'Connections/Get', ...args }); },
        async update(args: Omit<bottleneko.ConnectionsUpdateRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ConnectionsUpdateResponse>({ $type: 'Connections/Update', ...args }); },
        async delete(args: Omit<bottleneko.ConnectionsDeleteRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ConnectionsDeleteResponse>({ $type: 'Connections/Delete', ...args }); },
        async add(args: Omit<bottleneko.ConnectionsAddRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ConnectionsAddResponse>({ $type: 'Connections/Add', ...args }); },
        async getAttachmentUrl(args: Omit<bottleneko.ConnectionsGetAttachmentUrlRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ConnectionsGetAttachmentUrlResponse>({ $type: 'Connections/GetAttachmentUrl', ...args }); },
        async start(args: Omit<bottleneko.ConnectionsStartRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ConnectionsStartResponse>({ $type: 'Connections/Start', ...args }); },
        async restart(args: Omit<bottleneko.ConnectionsRestartRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ConnectionsRestartResponse>({ $type: 'Connections/Restart', ...args }); },
        async stop(args: Omit<bottleneko.ConnectionsStopRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ConnectionsStopResponse>({ $type: 'Connections/Stop', ...args }); },
        async test(args: Omit<bottleneko.ConnectionsTestRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ConnectionsTestResponse>({ $type: 'Connections/Test', ...args }); },
    };
    logging = {
        async log(args: Omit<bottleneko.LoggingLogRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.LoggingLogResponse>({ $type: 'Logging/Log', ...args }); },
        async subscribe(args: Omit<bottleneko.LoggingSubscribeRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.LoggingSubscribeResponse>({ $type: 'Logging/Subscribe', ...args }); },
        async unsubscribe(args: Omit<bottleneko.LoggingUnsubscribeRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.LoggingUnsubscribeResponse>({ $type: 'Logging/Unsubscribe', ...args }); },
    };
    messages = {
        async subscribe(args: Omit<bottleneko.MessagesSubscribeRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.MessagesSubscribeResponse>({ $type: 'Messages/Subscribe', ...args }); },
        async unsubscribe(args: Omit<bottleneko.MessagesUnsubscribeRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.MessagesUnsubscribeResponse>({ $type: 'Messages/Unsubscribe', ...args }); },
        async sendText(args: Omit<bottleneko.MessagesSendTextRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.MessagesSendTextResponse>({ $type: 'Messages/SendText', ...args }); },
    };
    script = {
        async getId(args: Omit<bottleneko.ScriptGetIdRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ScriptGetIdResponse>({ $type: 'Script/GetId', ...args }); },
        async getName(args: Omit<bottleneko.ScriptGetNameRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ScriptGetNameResponse>({ $type: 'Script/GetName', ...args }); },
    };
    #subscriptions = new Map<string, (letter: bottleneko.Letter) => Promise<void> | void>();

    constructor() {
        this.chatters = Object.fromEntries(Object.entries(this.chatters).map(([name, method]) => [name, method.bind(this)])) as typeof this.chatters;
        this.connections = Object.fromEntries(Object.entries(this.connections).map(([name, method]) => [name, method.bind(this)])) as typeof this.connections;
        this.logging = Object.fromEntries(Object.entries(this.logging).map(([name, method]) => [name, method.bind(this)])) as typeof this.logging;
        this.messages = Object.fromEntries(Object.entries(this.messages).map(([name, method]) => [name, method.bind(this)])) as typeof this.messages;
        this.script = Object.fromEntries(Object.entries(this.script).map(([name, method]) => [name, method.bind(this)])) as typeof this.script;
    }

    abstract call<T extends bottleneko.RpcResponse>(request: bottleneko.RpcRequest): Promise<ResultType<T, void>>;

    protected async onMail(mail: bottleneko.MailPacket) {
        const callback = this.#subscriptions.get(mail.subscriptionId.id);
        if (callback !== undefined) {
            for (const letter of mail.letters) {
                const result = callback(letter);
                if (result !== undefined) {
                    await result;
                }
            }
        }
    }

    async watch<T extends unknown[]>(args: T, subscribe: (...args: T) => Promise<bottleneko.SubscriptionId>, unsubscribe: (args: { subscriptionId: bottleneko.SubscriptionId }) => Promise<void>, callback: (letter: bottleneko.Letter) => Promise<void> | void) {
        const id = await subscribe(...args);
        this.#subscriptions.set(id.id, callback);
        return async () => {
            await unsubscribe({ subscriptionId: id });
            this.#subscriptions.delete(id.id);
        };
    }
};
