// Generated by Bottleneko.CodeGenerator

export interface DiscordProtocolConfiguration {
    $type: 'Discord';
    token: string;
    receiveEvents: boolean;
    isPresenceIntentEnabled: boolean;
    isServerMembersIntentEnabled: boolean;
    isMessageContentIntentEnabled: boolean;
    proxyId: string | null;
}

export type ProtocolConfiguration =
    DiscordProtocolConfiguration |
    TelegramProtocolConfiguration |
    TwitchProtocolConfiguration;

export interface TelegramProtocolConfiguration {
    $type: 'Telegram';
    token: string;
    receiveEvents: boolean;
    proxyId: string | null;
}

export enum TwitchSubscriptionTopic {
    ChannelCheer = 'ChannelCheer',
    ChannelUpdate = 'ChannelUpdate',
    ChannelFollow = 'ChannelFollow',
    ChannelAdBreakBegin = 'ChannelAdBreakBegin',
    ChannelChatMessage = 'ChannelChatMessage',
    ChannelSubscribe = 'ChannelSubscribe',
    ChannelSubscriptionEnd = 'ChannelSubscriptionEnd',
    ChannelSubscriptionGift = 'ChannelSubscriptionGift',
    ChannelSubscriptionMessage = 'ChannelSubscriptionMessage',
    ChannelRaidTo = 'ChannelRaidTo',
    ChannelRaidFrom = 'ChannelRaidFrom',
    ChannelBan = 'ChannelBan',
    ChannelUnban = 'ChannelUnban',
    ChannelModeratorAdd = 'ChannelModeratorAdd',
    ChannelModeratorRemove = 'ChannelModeratorRemove',
    ChannelChannelPointsCustomRewardAdd = 'ChannelChannelPointsCustomRewardAdd',
    ChannelChannelPointsCustomRewardUpdate = 'ChannelChannelPointsCustomRewardUpdate',
    ChannelChannelPointsCustomRewardRemove = 'ChannelChannelPointsCustomRewardRemove',
    ChannelChannelPointsCustomRewardRedemptionAdd = 'ChannelChannelPointsCustomRewardRedemptionAdd',
    ChannelChannelPointsCustomRewardRedemptionUpdate = 'ChannelChannelPointsCustomRewardRedemptionUpdate',
    ChannelPollBegin = 'ChannelPollBegin',
    ChannelPollProgress = 'ChannelPollProgress',
    ChannelPollEnd = 'ChannelPollEnd',
    ChannelPredictionBegin = 'ChannelPredictionBegin',
    ChannelPredictionProgress = 'ChannelPredictionProgress',
    ChannelPredictionLock = 'ChannelPredictionLock',
    ChannelPredictionEnd = 'ChannelPredictionEnd',
    ChannelSuspiciousUserUpdate = 'ChannelSuspiciousUserUpdate',
    ChannelSuspiciousUserMessage = 'ChannelSuspiciousUserMessage',
    ChannelVipAdd = 'ChannelVipAdd',
    ChannelVipRemove = 'ChannelVipRemove',
    ChannelWarningAcknowledge = 'ChannelWarningAcknowledge',
    ChannelWarningSend = 'ChannelWarningSend',
    ChannelHypeTrainBegin = 'ChannelHypeTrainBegin',
    ChannelHypeTrainProgress = 'ChannelHypeTrainProgress',
    ChannelHypeTrainEnd = 'ChannelHypeTrainEnd',
    ChannelCharityCampaignDonate = 'ChannelCharityCampaignDonate',
    ChannelCharityCampaignStart = 'ChannelCharityCampaignStart',
    ChannelCharityCampaignProgress = 'ChannelCharityCampaignProgress',
    ChannelCharityCampaignStop = 'ChannelCharityCampaignStop',
    ChannelShieldModeBegin = 'ChannelShieldModeBegin',
    ChannelShieldModeEnd = 'ChannelShieldModeEnd',
    ChannelShoutoutCreate = 'ChannelShoutoutCreate',
    ChannelShoutoutReceive = 'ChannelShoutoutReceive',
    ChannelGoalBegin = 'ChannelGoalBegin',
    ChannelGoalProgress = 'ChannelGoalProgress',
    ChannelGoalEnd = 'ChannelGoalEnd',
    StreamOnline = 'StreamOnline',
    StreamOffline = 'StreamOffline',
    UserUpdate = 'UserUpdate',
    UserWhisperMessage = 'UserWhisperMessage',
}

export enum TwitchScope {
    AnalyticsReadExtensions = 'AnalyticsReadExtensions',
    AnalyticsReadGames = 'AnalyticsReadGames',
    BitsRead = 'BitsRead',
    ChannelBot = 'ChannelBot',
    ChannelEditCommercial = 'ChannelEditCommercial',
    ChannelManageAds = 'ChannelManageAds',
    ChannelManageBroadcast = 'ChannelManageBroadcast',
    ChannelManageExtensions = 'ChannelManageExtensions',
    ChannelManageGuestStar = 'ChannelManageGuestStar',
    ChannelManageModerators = 'ChannelManageModerators',
    ChannelManagePolls = 'ChannelManagePolls',
    ChannelManagePredictions = 'ChannelManagePredictions',
    ChannelManageRaids = 'ChannelManageRaids',
    ChannelManageRedemptions = 'ChannelManageRedemptions',
    ChannelManageSchedule = 'ChannelManageSchedule',
    ChannelManageVideos = 'ChannelManageVideos',
    ChannelManageVips = 'ChannelManageVips',
    ChannelModerate = 'ChannelModerate',
    ChannelReadAds = 'ChannelReadAds',
    ChannelReadCharity = 'ChannelReadCharity',
    ChannelReadEditors = 'ChannelReadEditors',
    ChannelReadGoals = 'ChannelReadGoals',
    ChannelReadGuestStar = 'ChannelReadGuestStar',
    ChannelReadHypeTrain = 'ChannelReadHypeTrain',
    ChannelReadPolls = 'ChannelReadPolls',
    ChannelReadPredictions = 'ChannelReadPredictions',
    ChannelReadRedemptions = 'ChannelReadRedemptions',
    ChannelReadStreamKey = 'ChannelReadStreamKey',
    ChannelReadSubscriptions = 'ChannelReadSubscriptions',
    ChannelReadVips = 'ChannelReadVips',
    ClipsEdit = 'ClipsEdit',
    ModerationRead = 'ModerationRead',
    ModeratorManageAnnouncements = 'ModeratorManageAnnouncements',
    ModeratorManageAutomod = 'ModeratorManageAutomod',
    ModeratorManageAutomodSettings = 'ModeratorManageAutomodSettings',
    ModeratorManageBannedUsers = 'ModeratorManageBannedUsers',
    ModeratorManageBlockedTerms = 'ModeratorManageBlockedTerms',
    ModeratorManageChatMessages = 'ModeratorManageChatMessages',
    ModeratorManageChatSettings = 'ModeratorManageChatSettings',
    ModeratorManageGuestStar = 'ModeratorManageGuestStar',
    ModeratorManageShieldMode = 'ModeratorManageShieldMode',
    ModeratorManageShoutouts = 'ModeratorManageShoutouts',
    ModeratorManageUnbanRequests = 'ModeratorManageUnbanRequests',
    ModeratorManageWarnings = 'ModeratorManageWarnings',
    ModeratorReadAutomodSettings = 'ModeratorReadAutomodSettings',
    ModeratorReadBannedUsers = 'ModeratorReadBannedUsers',
    ModeratorReadBlockedTerms = 'ModeratorReadBlockedTerms',
    ModeratorReadChatMessages = 'ModeratorReadChatMessages',
    ModeratorReadChatSettings = 'ModeratorReadChatSettings',
    ModeratorReadChatters = 'ModeratorReadChatters',
    ModeratorReadFollowers = 'ModeratorReadFollowers',
    ModeratorReadGuestStar = 'ModeratorReadGuestStar',
    ModeratorReadModerators = 'ModeratorReadModerators',
    ModeratorReadShieldMode = 'ModeratorReadShieldMode',
    ModeratorReadShoutouts = 'ModeratorReadShoutouts',
    ModeratorReadSuspiciousUsers = 'ModeratorReadSuspiciousUsers',
    ModeratorReadUnbanRequests = 'ModeratorReadUnbanRequests',
    ModeratorReadVips = 'ModeratorReadVips',
    ModeratorReadWarnings = 'ModeratorReadWarnings',
    UserBot = 'UserBot',
    UserEdit = 'UserEdit',
    UserEditBroadcast = 'UserEditBroadcast',
    UserManageBlockedUsers = 'UserManageBlockedUsers',
    UserManageChatColor = 'UserManageChatColor',
    UserManageWhispers = 'UserManageWhispers',
    UserReadBlockedUsers = 'UserReadBlockedUsers',
    UserReadBroadcast = 'UserReadBroadcast',
    UserReadChat = 'UserReadChat',
    UserReadEmail = 'UserReadEmail',
    UserReadEmotes = 'UserReadEmotes',
    UserReadFollows = 'UserReadFollows',
    UserReadModeratedChannels = 'UserReadModeratedChannels',
    UserReadSubscriptions = 'UserReadSubscriptions',
    UserReadWhispers = 'UserReadWhispers',
    UserWriteChat = 'UserWriteChat',
}

export interface TwitchAuth {
    clientId: string;
    me: string;
    accessToken: string;
    refreshToken: string;
    scopes: TwitchScope[];
}

export interface TwitchProtocolChannel {
    name: string;
    eventSubscriptions: TwitchSubscriptionTopic[];
}

export interface TwitchProtocolConfiguration {
    $type: 'Twitch';
    auth: TwitchAuth;
    receiveEvents: boolean;
    channels: TwitchProtocolChannel[];
    proxyId: string | null;
}

export interface AuthenticatePacket {
    $type: 'Authenticate';
    accessToken: string;
}

export interface LogLetter {
    $type: 'Log';
    id: string;
    timestamp: string;
    severity: LogSeverity;
    sourceType: LogSourceType;
    sourceId: string;
    category: string;
    text: string;
}

export interface ChatMessageLetter {
    $type: 'ChatMessage';
    content: ChatMessageDto;
}

export type Letter =
    LogLetter |
    ChatMessageLetter;

export interface MailPacket {
    $type: 'Mail';
    subscriptionId: string;
    letters: Letter[];
}

export type Packet =
    AuthenticatePacket |
    SubscribePacket |
    MailPacket |
    UnsubscribePacket;

export interface SubscribePacket {
    $type: 'Subscribe';
    id: string;
    topic: SubscriptionTopic;
    beforeId: string | null;
}

export interface LogFilter {
    severities: LogSeverity[] | null;
    sourceType: LogSourceType | null;
    sourceId: string | null;
    category: string | null;
}

export interface LogsSubscriptionTopic {
    $type: 'Logs';
    filter: LogFilter;
}

export interface ChatMessageFilter {
    connectionId: string | null;
}

export interface ChatMessagesSubscriptionTopic {
    $type: 'ChatMessages';
    filter: ChatMessageFilter;
}

export type SubscriptionTopic =
    LogsSubscriptionTopic |
    ChatMessagesSubscriptionTopic;

export interface UnsubscribePacket {
    $type: 'Unsubscribe';
    id: string;
}

export interface GraphNodePortRef {
    nodeId: string;
    portId: string;
}

export interface GraphNodePosition {
    x: number;
    y: number;
}

export interface GraphNode {
    id: string;
    position: GraphNodePosition;
    data: GraphNodeData;
}

export interface GraphConnection {
    id: string;
    source: GraphNodePortRef;
    target: GraphNodePortRef;
}

export interface GraphScriptCode {
    $type: 'Graph';
    nodes: GraphNode[];
    connections: GraphConnection[];
}

export interface GraphIfNodeData {
    $type: 'if';
}

export interface GraphIfValidNodeData {
    $type: 'if-valid';
}

export interface GraphSwitchNodeData {
    $type: 'switch';
    inputType: GraphSocketType | null;
}

export interface GraphMessageReceivedNodeData {
    $type: 'message-received-event';
}

export interface GraphAddNodeData {
    $type: 'add';
}

export interface GraphAverageNodeData {
    $type: 'average';
}

export interface GraphCeilNodeData {
    $type: 'ceil';
}

export interface GraphCheckNumberNodeData {
    $type: 'check-number';
}

export interface GraphDivideNodeData {
    $type: 'divide';
}

export interface GraphFloorNodeData {
    $type: 'floor';
}

export interface GraphLog2NodeData {
    $type: 'log2';
}

export interface GraphLog10NodeData {
    $type: 'log10';
}

export interface GraphLogNodeData {
    $type: 'log';
}

export interface GraphMaxNodeData {
    $type: 'max';
}

export interface GraphMinNodeData {
    $type: 'min';
}

export interface GraphMultiplyNodeData {
    $type: 'multiply';
}

export interface GraphNegateNodeData {
    $type: 'negate';
}

export interface GraphPowerNodeData {
    $type: 'power';
}

export interface GraphRandomNumberNodeData {
    $type: 'random-number';
}

export interface GraphRandomRangeNodeData {
    $type: 'random-range';
    integers: boolean;
}

export interface GraphRemainderNodeData {
    $type: 'remainder';
}

export interface GraphRoundNodeData {
    $type: 'round';
}

export interface GraphSignNodeData {
    $type: 'sign';
}

export interface GraphSqrtNodeData {
    $type: 'sqrt';
}

export interface GraphSubtractNodeData {
    $type: 'subtract';
}

export interface GraphSwitchOnSignNodeData {
    $type: 'switch-on-sign';
}

export interface GraphConcatNodeData {
    $type: 'concat';
    inputs: number;
}

export interface GraphFormatTextNodeData {
    $type: 'format-text';
    format: string;
}

export interface GraphLogMessageNodeData {
    $type: 'log-message';
    severity: LogSeverity;
}

export interface GraphSplitStructureNodeData {
    $type: 'split-structure';
    inputType: GraphSocketType | null;
}

export type GraphNodeData =
    GraphIfNodeData |
    GraphIfValidNodeData |
    GraphSwitchNodeData |
    GraphMessageReceivedNodeData |
    GraphAddNodeData |
    GraphAverageNodeData |
    GraphCeilNodeData |
    GraphCheckNumberNodeData |
    GraphDivideNodeData |
    GraphFloorNodeData |
    GraphLog2NodeData |
    GraphLog10NodeData |
    GraphLogNodeData |
    GraphMaxNodeData |
    GraphMinNodeData |
    GraphMultiplyNodeData |
    GraphNegateNodeData |
    GraphPowerNodeData |
    GraphRandomNumberNodeData |
    GraphRandomRangeNodeData |
    GraphRemainderNodeData |
    GraphRoundNodeData |
    GraphSignNodeData |
    GraphSqrtNodeData |
    GraphSubtractNodeData |
    GraphSwitchOnSignNodeData |
    GraphConcatNodeData |
    GraphFormatTextNodeData |
    GraphLogMessageNodeData |
    GraphSplitStructureNodeData;

export interface GraphInvalidSocketType {
    $type: 'invalid';
}

export interface GraphExecSocketType {
    $type: 'exec';
}

export interface GraphBooleanSocketType {
    $type: 'boolean';
}

export interface GraphNumberSocketType {
    $type: 'number';
}

export interface GraphStringSocketType {
    $type: 'string';
}

export interface GraphIdSocketType {
    $type: 'id';
}

export interface GraphProtocolSocketType {
    $type: 'protocol';
}

export interface GraphTimestampSocketType {
    $type: 'timestamp';
}

export interface GraphChatSocketType {
    $type: 'chat';
}

export interface GraphChatMessageSocketType {
    $type: 'chat-message';
}

export interface GraphChatterSocketType {
    $type: 'chatter';
}

export interface GraphAnyStructureInputSocketType {
    $type: 'any-structure';
}

export interface GraphAnyEnumInputSocketType {
    $type: 'any-enum';
}

export interface GraphAnyOptionalInputSocketType {
    $type: 'any-optional';
}

export interface GraphOptionalSocketType {
    $type: 'optional';
    innerType: GraphSocketType;
}

export type GraphSocketType =
    GraphInvalidSocketType |
    GraphExecSocketType |
    GraphBooleanSocketType |
    GraphNumberSocketType |
    GraphStringSocketType |
    GraphIdSocketType |
    GraphProtocolSocketType |
    GraphTimestampSocketType |
    GraphChatSocketType |
    GraphChatMessageSocketType |
    GraphChatterSocketType |
    GraphAnyStructureInputSocketType |
    GraphAnyEnumInputSocketType |
    GraphAnyOptionalInputSocketType |
    GraphOptionalSocketType;

export interface AttachmentDto {
    id: string;
    name: string | null;
    contentType: string;
}

export interface ChatterSummaryDto {
    id: string;
    name: string;
}

export interface ChatSummaryDto {
    id: string;
    name: string;
}

export interface ChatMessageDto {
    id: string;
    connectionId: string;
    timestamp: string;
    chat: ChatSummaryDto;
    author: ChatterSummaryDto;
    textContent: string | null;
    attachments: AttachmentDto[];
    isSpecial: boolean;
    isDirect: boolean;
    isMissed: boolean;
}

export enum ConnectionStatus {
    NotConnected = 'NotConnected',
    Connecting = 'Connecting',
    Connected = 'Connected',
    Reconnecting = 'Reconnecting',
    DelayedReconnect = 'DelayedReconnect',
    Stopping = 'Stopping',
    Error = 'Error',
}

export enum Protocol {
    Discord = 'Discord',
    Telegram = 'Telegram',
    Twitch = 'Twitch',
}

export interface ExtendedConnectionStatus {
    status: ConnectionStatus;
    statusChangeDelay: number;
}

export interface ConnectionDto {
    id: string;
    name: string;
    protocol: Protocol;
    autoStart: boolean;
    config: ProtocolConfiguration;
    extendedStatus: ExtendedConnectionStatus;
}

export interface SystemInfoDto {
    hostname: string;
    operatingSystem: string;
    arch: string;
    dotNetVersion: string;
    currentTime: string;
    uptime: number;
}

export interface NekoInfoDto {
    version: string;
    uptime: number;
}

export interface EnvironmentInfoDto {
    system: SystemInfoDto;
    neko: NekoInfoDto;
}

export interface ActivityStatsItemDto {
    period: string;
    totalMessages: number;
    messagesPerMinute: number;
}

export interface ActivityStatsDto {
    items: ActivityStatsItemDto[];
}

export enum ProxyType {
    Http = 'Http',
    Https = 'Https',
    Socks4 = 'Socks4',
    Socks4a = 'Socks4a',
    Socks5 = 'Socks5',
}

export interface ProxyDto {
    id: string;
    name: string;
    type: ProxyType;
    hostname: string;
    port: number;
    isAuthRequired: boolean;
    username: string;
    password: string;
}

export enum ScriptStatus {
    Stopped = 'Stopped',
    Starting = 'Starting',
    Running = 'Running',
    Restarting = 'Restarting',
    Stopping = 'Stopping',
    Error = 'Error',
}

export type ScriptCode =
    JsScriptCode |
    GraphScriptCode;

export interface JsScriptCode {
    $type: 'JavaScript';
    source: string;
}

export interface ScriptDto {
    id: string;
    name: string;
    description: string;
    autoStart: boolean;
    code: ScriptCode;
    status: ScriptStatus;
}

export interface UserDto {
    id: string;
    login: string;
    displayName: string;
}

export enum LogSourceType {
    System = 'System',
    Connection = 'Connection',
    Script = 'Script',
}

export enum LogSeverity {
    Critical = 'Critical',
    Error = 'Error',
    Warning = 'Warning',
    Info = 'Info',
    Verbose = 'Verbose',
    Debug = 'Debug',
}
