// Generated by Bottleneko.CodeGenerator

import type * as bottleneko from './bottleneko.gen.ts';

export type ResultType<T, Default> = 'result' extends keyof T ? T['result'] : Default;

export default abstract class AbstractRpc {
    script = {
        getId(args: Omit<bottleneko.GetIdRequest, '$type'>) { return (this as unknown as AbstractRpc).call<bottleneko.GetIdResponse>({ $type: 'Script/GetId', ...args }); },
        doSomething(args: Omit<bottleneko.DoSomethingRequest, '$type'>) { return (this as unknown as AbstractRpc).call<bottleneko.DoSomethingResponse>({ $type: 'Script/DoSomething', ...args }); },
        doSomethingA(args: Omit<bottleneko.DoSomethingARequest, '$type'>) { return (this as unknown as AbstractRpc).call<bottleneko.DoSomethingAResponse>({ $type: 'Script/DoSomethingA', ...args }); },
        getName(args: Omit<bottleneko.GetNameRequest, '$type'>) { return (this as unknown as AbstractRpc).call<bottleneko.GetNameResponse>({ $type: 'Script/GetName', ...args }); },
        doCrimes(args: Omit<bottleneko.DoCrimesRequest, '$type'>) { return (this as unknown as AbstractRpc).call<bottleneko.DoCrimesResponse>({ $type: 'Script/DoCrimes', ...args }); },
    };

    constructor() {
        this.script = Object.fromEntries(Object.entries(this.script).map(([name, method]) => [name, method.bind(this)])) as typeof this.script;
    }

    abstract call<T extends bottleneko.RpcResponse>(request: bottleneko.RpcRequest): Promise<ResultType<T, void>>;
};
