// Generated by Bottleneko.CodeGenerator
/* eslint-disable @typescript-eslint/no-confusing-void-expression */

import type * as bottleneko from './bottleneko.gen.ts';

export type ResultType<T, Default> = 'result' extends keyof T ? T['result'] : Default;

export default abstract class AbstractRpc {
    logging = {
        async log(args: Omit<bottleneko.LoggingLogRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.LoggingLogResponse>({ $type: 'Logging/Log', ...args }); },
        async subscribe(args: Omit<bottleneko.LoggingSubscribeRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.LoggingSubscribeResponse>({ $type: 'Logging/Subscribe', ...args }); },
        async unsubscribe(args: Omit<bottleneko.LoggingUnsubscribeRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.LoggingUnsubscribeResponse>({ $type: 'Logging/Unsubscribe', ...args }); },
    };
    messages = {
        async subscribe(args: Omit<bottleneko.MessagesSubscribeRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.MessagesSubscribeResponse>({ $type: 'Messages/Subscribe', ...args }); },
        async unsubscribe(args: Omit<bottleneko.MessagesUnsubscribeRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.MessagesUnsubscribeResponse>({ $type: 'Messages/Unsubscribe', ...args }); },
    };
    script = {
        async getId(args: Omit<bottleneko.ScriptGetIdRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ScriptGetIdResponse>({ $type: 'Script/GetId', ...args }); },
        async getName(args: Omit<bottleneko.ScriptGetNameRequest, '$type'>) { return await (this as unknown as AbstractRpc).call<bottleneko.ScriptGetNameResponse>({ $type: 'Script/GetName', ...args }); },
    };
    #subscriptions = new Map<string, (letter: bottleneko.Letter) => Promise<void> | void>();

    constructor() {
        this.logging = Object.fromEntries(Object.entries(this.logging).map(([name, method]) => [name, method.bind(this)])) as typeof this.logging;
        this.messages = Object.fromEntries(Object.entries(this.messages).map(([name, method]) => [name, method.bind(this)])) as typeof this.messages;
        this.script = Object.fromEntries(Object.entries(this.script).map(([name, method]) => [name, method.bind(this)])) as typeof this.script;
    }

    abstract call<T extends bottleneko.RpcResponse>(request: bottleneko.RpcRequest): Promise<ResultType<T, void>>;

    protected async onMail(mail: bottleneko.MailPacket) {
        const callback = this.#subscriptions.get(mail.subscriptionId.id);
        if (callback !== undefined) {
            for (const letter of mail.letters) {
                const result = callback(letter);
                if (result !== undefined) {
                    await result;
                }
            }
        }
    }

    async watch<T extends unknown[]>(args: T, subscribe: (...args: T) => Promise<bottleneko.SubscriptionId>, unsubscribe: (args: { subscriptionId: bottleneko.SubscriptionId }) => Promise<void>, callback: (letter: bottleneko.Letter) => Promise<void> | void) {
        const id = await subscribe(...args);
        this.#subscriptions.set(id.id, callback);
        return async () => {
            await unsubscribe({ subscriptionId: id });
            this.#subscriptions.delete(id.id);
        };
    }
};
